### ISSUE TITLE
No repository for "User" was found.

### ISSUE THREAD

**Issue by michalkow** [traduora/traduora#10]
**Describe the bug**
On app start, I receive this error.

**To Reproduce**
1. Follow steps in installation from the source instruction
2. Run app

**Expected behavior**
App will run

** Environment (please complete the following information):**
 - Device: Desktop
 - OS: MacOS 10.13.6 

**Additional context**
[Nest] 1501   - 2019-3-12 17:38:27   [NestFactory] Starting Nest application...
[Nest] 1501   - 2019-3-12 17:38:27   [InstanceLoader] PassportModule dependencies initialized +101ms
[Nest] 1501   - 2019-3-12 17:38:27   [InstanceLoader] TypeOrmModule dependencies initialized +0ms
[Nest] 1501   - 2019-3-12 17:38:27   [InstanceLoader] JwtModule dependencies initialized +0ms
[Nest] 1501   - 2019-3-12 17:38:28   [InstanceLoader] TypeOrmCoreModule dependencies initialized +70ms
[Nest] 1501   - 2019-3-12 17:38:28   [ExceptionHandler] No repository for "User" was found. Looks like this entity is not registered in current "default" connection? +1ms
RepositoryNotFoundError: No repository for "User" was found. Looks like this entity is not registered in current "default" connection?
    at new RepositoryNotFoundError (/Users/mac/Projects/traduora/dist/node_modules/typeorm/error/RepositoryNotFoundError.js:20:28)

**Comment by anthonynsimon** [comment]
Hey, just a couple of questions: do you have any configuration override? are you running it via the docker image or a fresh build from source?

**Comment by michalkow** [comment]
It is fresh build from source. Here is my configuration:
`
NODE_ENV=dev
TR_PORT=8080
TR_SECRET=Mysecret
TR_VIRTUAL_HOST=traduora.mydomain.com

TR_DB_HOST=127.0.0.1
TR_DB_PORT=3306
TR_DB_DATABASE=tr_dev
TR_DB_USER=root
TR_DB_PASSWORD=mypassword

TR_CORS_ENABLED=false
TR_ACCESS_LOGS_ENABLED=true
TR_AUTH_TOKEN_EXPIRES=86400
TR_SIGNUPS_ENABLED=true
TR_MAX_PROJECTS_PER_USER=100
TR_DEFAULT_PROJECT_PLAN=open-source
TR_DB_AUTOMIGRATE=true

TR_MAIL_DEBUG=false
TR_MAIL_SENDER=no-reply@localhost.com
TR_MAIL_HOST=smtp.ethereal.email
TR_MAIL_PORT=587
TR_MAIL_SECURE=false
TR_MAIL_USER=l4kzu3nw7o4x45wz@ethereal.email
TR_MAIL_PASSWORD=3mJgh1g9dpMf3uZaBM
`

**Comment by anthonynsimon** [comment]
I'm only able to reproduce this if I start the application anywhere else other than the `dist` folder.

Assuming the following commands run from the project root:

Works:
```
cd dist
node dist/src/main.js
```

I get the same error posted:
```
node dist/src/main.js
```

**Comment by michalkow** [comment]
Thank you! That solved the problem for me!
