### ISSUE TITLE
Invite Emails Show 'localhost' instead of sitename. 

### ISSUE THREAD

**Issue by spooknik** [traduora/traduora#101]
**Describe the bug**
When inviting or receiving sign up emails the URL is localhost/XXXX instead of sitename. 

**To Reproduce**
1. Run via docker-compose up -d
2. Set up ngnix with reverse proxy for sitename
3. Sign up 

**Expected behavior**
Shows sitename instead of localhost

**Screenshots**
![image](https://user-images.githubusercontent.com/40317809/71670166-6063e280-2d6f-11ea-9e97-96d4722b643e.png)

**Environment (please complete the following information):**

 - Device: Server
 - OS: Ubuntu 18:04
 - Browser Chrome
 - Version 0.15.0

**Additional context**

**Comment by anthonynsimon** [comment]
You need to tell traduora under what host it is deployed. Check the TR_VIRTUAL_HOST env var in https://docs.traduora.com/docs/configuration

**Comment by spooknik** [comment]
I'm totally blind. Thank you :)

**Comment by anthonynsimon** [comment]
No worries! Glad to help :)
