### ISSUE TITLE
API authentication problems

### ISSUE THREAD

**Issue by spooknik** [traduora/traduora#102]
Hello! 

I am trying to automate exporting via a python script but i'm encountering some strange behavior trying to set things up. 

I've set up the API keys via the project settings. 

I can get a token like so: 

```python
import requests
data = {'grant_type': 'client_credentials', 'client_id': MY_CLIENT_ID', 'client_secret': 'MY_SECRET_KEY'}
hed = {'accept': 'application/json', 'Content-Type': 'application/json'}
url = 'https://TRADUORA_IS_COOL.COM/api/v1/auth/token'

response = requests.post(url, json=data, headers=hed)

print(response)
print(response.text)

<Response [200]>
{"access_token":"LONG TOKEN ID","token_type":"bearer","expires_in":"86400s"}
```

okay, cool. 

Now when I try to get the project stats right after the token: 

```python
headers = {"content-type":"application/json"}
response = requests.get('https://TRADUORA_IS_COOL.COM/api/v1/projects/PROJECT_ID/stats', 
print(response)

<Response [401]>
```

Similar story if I do the same via curl.

**Comment by spooknik** [comment]
Nevermind. I wasn't sending the token in the header. 💯 

Closing to avoid more shame.

**Comment by azlux** [comment]
@spooknik Can you paste the working code ? I do the same with requests and Bearer token, but still a 401 on my side.
