### ISSUE TITLE
Number of nested levels

### ISSUE THREAD

**Issue by BastienMbz** [traduora/traduora#110]
Hi,

I was trying to import json file with many nested level and I encountered an error with the message : "Malformed json file".

In the file api/src/formatters/jsonnested.ts (and the yaml-nested.ts) there is the following limit :

```
if (level >= 6) {
     throw new Error('Too many nested levels in JSON content');
}
```

I tried to modify the condition and rebuild the Docker image and it works.
I would like to know why there is a limit of 5 nested level ?

Thanks

**Comment by anthonynsimon** [comment]
Hi @BastienMbz 

The idea is to prevent an attacker from blocking the event loop for too long by uploading files with excessive nested fields. At the time the limit seemed sane, but I have increased it to `100` in #111 .

**Comment by BastienMbz** [comment]
Hi @anthonynsimon 

Thank you for the quick change, that solved my issue, but I see in your changes that you put the value in a const JSON_MAX_NESTED_LEVELS.
Wouldn't it be more interesting to put this limitation as environment variable (https://docs.traduora.com/docs/configuration) with a default value of 100 ?

Thanks

**Comment by anthonynsimon** [comment]
Yes, that’s a good idea. Thanks for the feedback!
