### ISSUE TITLE
Provide an option to pretty print exported JSON

### ISSUE THREAD

**Issue by coeing** [traduora/traduora#113]
**Is your feature request related to a problem? Please describe.**
We use Traduora as our translation management tool and work with the JSON Nested files in our project. The exported one-line JSON files are really hard to handle with, especially doing a Git Diff on them doesn't work.

**Describe the solution you'd like**
If the exported JSON files would be pretty printed (i.e. with spaces and line breaks) our workflow would be much better and we could see with a diff tool which translations changed in a commit.

**Describe alternatives you've considered**
We could use an external tool to format the JSON before doing our commits, but developers might forget it and check in the unformatted file.

**Additional context**
I already did some search and saw that the pretty printing is supported by the JSON.stringify method natively: https://stackoverflow.com/questions/4810841/pretty-print-json-using-javascript
So you might just have to change one line in the jsonNestedExporter to do the pretty printing. If it should be configurable it might be a bigger change though.

P.S.: Thanks for the great tool :)

**Comment by anthonynsimon** [comment]
Hey thanks for the feedback, makes sense, this will be included in the next release.

**Comment by coeing** [comment]
@anthonynsimon That's great, thank you very much! :) Is there already a planned release date?

**Comment by anthonynsimon** [comment]
@coeing Most likely in the coming days :)

**Comment by coeing** [comment]
Yay, even better :)

**Comment by anthonynsimon** [comment]
@coeing These changes are available in `0.16.0`. Let me know if anything

https://github.com/traduora/traduora/releases/tag/0.16.0

**Comment by anthonynsimon** [comment]
@coeing These changes are available in 0.16.0. Please let me know if anything

https://github.com/traduora/traduora/releases/tag/0.16.0

**Comment by coeing** [comment]
@anthonynsimon Great, thank you, we will install the new version soon. I'll let you know if any problems occur 👍
