### ISSUE TITLE
Apple Strings

### ISSUE THREAD

**Issue by BrunoMiguens** [traduora/traduora#13]
Hi, I'm an iOS developer who just found out your project, and congrats for the idea and effort.

**Apple Strings: Import & Export**
It would be awesome, to import and export terms and translations using Apple Strings (.strings) files without exporting or converting to another file.

For me the current state of the platform is enough to start migrating from the current solutions to yours, the only issue, is the import options are very limited.

I've not done much research regarding this feature, however, I'm interested and available to help contributing to the project as soon as possible.

**Comment by anthonynsimon** [comment]
Hey, that sounds great! Supporting Apple Strings is on the roadmap, so hopefully we can add it for one of the next releases.

Let me know if you'd like to give it a try.

For some pointers, you can start by checking out the formatter [interfaces](https://github.com/traduora/traduora/blob/master/api/src/domain/formatters.ts) and then by [adding](https://github.com/traduora/traduora/tree/master/api/src/formatters) one for Apple Strings.

**Comment by anthonynsimon** [comment]
@BrunoMiguens Thanks to the work done by @magyarosibotond, we now have Apple Strings support, it will be included in the next release sometime in the next days 🎉
