### ISSUE TITLE
TR_SIGNUPS_ENABLED=false does not work

### ISSUE THREAD

**Issue by ColinSchmale** [traduora/traduora#176]
**Describe the bug**
Setting TR_SIGNUPS_ENABLED=false does not disable user sign ups. "Don't have an account? Sign Up" is still there and users can still create a new account if they click on "Sign Up" and fill out the form.

**To Reproduce**
I'm using the newest version of Traduora and I deployed the project from source.

I've set the TR_SIGNUPS_ENABLED environment variable to false:
sudo nano /etc/environment
```
TR_VIRTUAL_HOST=http://translate.mywebsite.app
TR_DB_USER=traduora
TR_DB_PASSWORD=mypassword
TR_SIGNUPS_ENABLED=false
```

And I've restarted Traduora.

**Environment:**

- Device: VPS
- OS: Ubuntu Server
- Version: 18.0.4

**Comment by ColinSchmale** [comment]
I changed some other settings and now users get a "resource not found" when they try to register.  Maybe I just didn't restart the app the right way. 😄

**Comment by anthonynsimon** [comment]
Hey thanks for reporting this. Yes, we should improve the error messages and hide the signup page if the signups option is disabled.

Anyways, glad you were able to sort it out in the end.
