### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by vtolstov** [traduora/traduora#18]
I'm use zanata with own project, but it slow... I want to replace it with traduora, but it lacks client and api. Do you plan to add it?

**Comment by anthonynsimon** [comment]
Hey, traduora already has a REST API and it has support for API clients on most endpoints.

What is currently missing is the [documentation](https://docs.traduora.com/docs/api/v1/overview) for it, but this will be added in the coming weeks.

**Comment by vtolstov** [comment]
Thanks, so i'm wait for api and after that may be create api client for nodejs

**Comment by anthonynsimon** [comment]
Closing the issue, the docs for the API are now available at https://docs.traduora.com/docs/api/v1/swagger/
