### ISSUE TITLE
Add CLA Bot

### ISSUE THREAD

**Issue by diego-vieira** [traduora/traduora#2]
**Is your feature request related to a problem? Please describe.**
To make it easier for new contributors to sign the CLA.

**Describe the solution you'd like**
Use a bot instead.

Either option should do.

- https://github.com/cla-assistant/cla-assistant
- https://github.com/clabot/clabot

**Comment by anthonynsimon** [comment]
Hey thanks for the suggestion, I've integrated the repo with cla-assistant.
