### ISSUE TITLE
Consistent translation export

### ISSUE THREAD

**Issue by sodik82** [traduora/traduora#21]
**Is your feature request related to a problem? Please describe.**
I have imported our properties files and then exported it again. The terms were exported in  quite random way. This makes it hard to track changes between two versions.

**Describe the solution you'd like**
Ideally the order of terms after export would remain the same as in the imported file. This should apply also for other languages. 

**Describe alternatives you've considered**
As it might be "hard" to manage order of items (also in case when someone add terms via GUI) alphabetical order of terms (in UI and exports) will improve the predictability to the exported files.

**Comment by anthonynsimon** [comment]
Hey thanks for reporting the issue, I agree that it would be better for the ordering of the terms to be predictable, will try alphabetical order (ascending) and let you know 👍

**Comment by anthonynsimon** [comment]
This is fixed in #23
