### ISSUE TITLE
Chinese input is not supported. The problem can be solved by modifying mysql character code to UTF8.

### ISSUE THREAD

**Issue by LincWong** [traduora/traduora#28]
**Describe the bug**
Chinese input is not supported. The problem can be solved by modifying mysql character code to UTF8.

**To Reproduce**
1. input some Chinese term
2. console will show some error

Chinese input is not supported. The problem can be solved by modifying mysql character code to UTF8.

**Comment by anthonynsimon** [comment]
Hi @LincWong 

Just yesterday we released version `0.10.0` which includes the fix. Just be sure to pull the latest docker image to try it out (or pull master if building from source):

```
docker pull traduora/traduora
```

Let me know :)

**Comment by anthonynsimon** [comment]
Closing the issue, feel free to re-open it in case the issue persists.
