### ISSUE TITLE
Is there an option to share translation strings between projects?

### ISSUE THREAD

**Issue by mobiniusgovardhan** [traduora/traduora#33]
**Is your feature request related to a problem? 
Is there an option to share translation strings between projects instead of editing manually in all projects?

**Describe the solution you'd like**
Shared strings that replicate at all projects

**Comment by anthonynsimon** [comment]
Hi @mobiniusgovardhan, at the moment it is not possible to do so. I'm closing the issue for now since I'm unsure if this will be added in the future as it would require major changes to how data is structured at the database level.
