### ISSUE TITLE
How do users who have forgotten their password reset their password? Traduora can't send a reset email to the company's internal private mailbox

### ISSUE THREAD

**Issue by LincWong** [traduora/traduora#35]

**Comment by LincWong** [comment]
@anthonynsimon

**Comment by anthonynsimon** [comment]
Hi, did you configure the mail server?

**Comment by LincWong** [comment]
Our company does not support the SMTP protocol for security reasons... :(  

another question, can we create a super admin accoun for check all project in our system ？

**Comment by LincWong** [comment]
In addition to the mailbox, is there any way to retrieve the password?？

**Comment by anthonynsimon** [comment]
It’s possible to get the passport reset link by enabling mail debug mode
via the server env variables and looking at the server logs when requesting
the passport reset.

A link to the intercepted outgoing email will appear.

Let me know if that helps.

**Comment by LincWong** [comment]
let me try the env variables, if them work, i will close this issue, thank u~

**Comment by LincWong** [comment]
@anthonynsimon 
After I modified the environment variables, it still can't work. 

and then I checked the source code and found that the problem: 

https://github.com/traduora/traduora/blame/master/api/src/services/mail.service.ts#L86-L89

the `console.log` do not execute after the yield exception. I can print out the link to reset the password after I edit the code.

buy i hope you can update the project as soon as possible~ Thank you very much~

**Comment by anthonynsimon** [comment]
@LincWong I was able to enable the logging to console via the environment variable `TR_MAIL_DEBUG=true`, how did you set it when it didn't work for you?

**Comment by anthonynsimon** [comment]
I'm closing the issue, feel free to re-open it in case the issue persists.

**Comment by LincWong** [comment]
TR_MAIL_DEBUG=true is work and it can go into the logic of printing the log.

However, due to the previous mail sending logic exception (SMTP server exception), it is impossible to print to the log.

I mean, you need to print the log ahead of time, don't put it after the email is sent.

Specific code: https://github.com/traduora/traduora/blame/master/api/src/services/mail.service.ts#L86-L89

**Comment by LincWong** [comment]
before:
```
const res = await this.transporter.sendMail(message);
if (config.mail.debug) {
    console.log(`Mail sent. Preview url: ${getTestMessageUrl(res)}`);
}
```

after:
```
if (config.mail.debug) {
    console.log(`Mail sent. Preview url: ${getTestMessageUrl(res)}`);
}
const res = await this.transporter.sendMail(message);
```

**Comment by anthonynsimon** [comment]
Thanks for the feedback. I was checking it out, but it seems that the helper function `getTestMessageUrl` from nodemailer needs the already sent message info, so it's seems not possible to print the debug URL without attempting to send the message first :(

Here's some more info: https://nodemailer.com/smtp/testing/
