### ISSUE TITLE
Can the length limit of translation terms be relaxed? The current limit length is 255

### ISSUE THREAD

**Issue by LincWong** [traduora/traduora#39]
When the limit is exceeded, the json file cannot be imported to the traduora system without any illegal characters.

![image](https://user-images.githubusercontent.com/1209664/58846906-76afa000-86b3-11e9-9bb3-b3754506b0a5.png)

**Comment by anthonynsimon** [comment]
Unfortunately the terms would have to remain limited to 255 characters, as that is the maximum for an indexed field on MySQL with UTF-8 encoding.

I'm closing the issue for now, as it seems unlikely that this would change for the upcoming releases :(
