### ISSUE TITLE
Add OAuth

### ISSUE THREAD

**Issue by iilei** [traduora/traduora#41]
**Is your feature request related to a problem? Please describe.**
- Individual passwords for a variety of services lead many people to chose weak / same passwords over and over again. 

**Describe the solution you'd like**
As _administrator_ I would like the possibility to activate "login with <OAuth v2 Provider XYZ>" 
with options like

- keycloak (opinionated preference)
- github
- facebook
- paypal
- linkedin 
- bitbucket

And as a _new user_ who is onboarding I would like to be able to register using one of the options besides the existing option (email)

**Describe alternatives you've considered**
As OAuth seems to be a widely adopted standard, no other options considered

**Additional context**
Personally I would be using keycloak if possible.

**Comment by stepotronic** [comment]
I like this idea. I guess it would be a great option to allow to configure the urls and ofc extend the software with your own implementation.

**Comment by anthonynsimon** [comment]
Sounds great! Will try and make some time for this in the coming weeks, but feel free if anybody wants to give it a go :)

**Comment by anthonynsimon** [comment]
Thanks to @anymaniax work, we should now be able to support multiple OAuth providers going forward 🎉 https://github.com/traduora/traduora/pull/44

The relevant code is on master but hasn't been released yet, I think we should add a couple more integrations to ensure that we can handle differences between providers with the current implementation.
