### ISSUE TITLE
Configurable Plans

### ISSUE THREAD

**Issue by MatteoJoliveau** [traduora/traduora#45]
**Is your feature request related to a problem? Please describe.**
I can't seem to find how to manage plans, either in the UI or in the API

**Describe the solution you'd like**
As a system administrator I would like to be able to create and manage plans and quotas, and to assign them to projects

**Describe alternatives you've considered**
At the moment the default is the `open-source` plan, which has only 100k strings

**Comment by anthonynsimon** [comment]
Right now it is not possible to manage plans via the UI as this is intended
as part of the future SaaS offering.

In the future we might build an admin UI (PR’s welcome :) ), but for now it
can only be done via connecting to the DB and adding the row to the plans
table.

This should not a problem as long as your use of the project is within what
the AGPL license allows.

**Comment by MatteoJoliveau** [comment]
Understood. As I mentioned in the other PR, we intend to use it to manage translations for a product we're building. As we do not intend to compete with your upcoming SaaS, we'll gladly contribute back any feature or bugfix we might end up developing.

For now, I guess we'll have to manage the plans manually. Is there an "unlimited" plan or something similar? Otherwise, I'll set a very high number and call it a day :)

**Comment by anthonynsimon** [comment]
No worries :) I think the best would be to put a sufficiently high limit.
It can always be updated in case it’s needed anyways and it will persist if
you update your version of traduora.
