### ISSUE TITLE
Maximum term length is 255 characters

### ISSUE THREAD

**Issue by tmosmant** [traduora/traduora#6]
**Is your feature request related to a problem? Please describe.**
This project really look awesome but I won't be able to use it without the add of the JSON with plaintext keys format support. Using the JSON flat format doesn't work for me as I get a `500 Internal Server Error`.

**Describe the solution you'd like**
Support translation files formatted like this one:
```json
{
    "Project": "Projekt",
    "Name of the project.": "Name des Projekts",
    "Empty! No entries added yet.": "Leer! Es sind noch keine Einträge vorhanden.",
    "Ok.": "Ok."
}
```

**Describe alternatives you've considered**
Rewrite all of my templates 😂 I'm well aware this format isn't the most appropriate one but it's the one I use since 4 years on my project.

**Comment by anthonynsimon** [comment]
@tmosmant thanks for the feedback, I tried it out and it seems to be working with the example that you posted. Are you selecting the correct JSON format on import/export?

**Comment by tmosmant** [comment]
After some digging, I found where the problem is: as I've sentences as terms, some of them can be pretty long and it seems that traduora doesn't support terms with more than 255 characters. Nothing to do with the format 🎉
Is there an easy fix for this? My longest term would be ~500 chars.

**Comment by anthonynsimon** [comment]
Unfortunately I don't think it would be possible 😞 there are some limitations on the terms length since they are indexed on the DB.

Maybe once the libraries to help integrate with traduora are available (working on that), there could be an option to transparently handle these cases by computing and id out of the term on import.

**Comment by anthonynsimon** [comment]
Hang on, I might be wrong on that. Let me check it out later today.

**Comment by anthonynsimon** [comment]
Sorry for not having better news, but unfortunately the terms would have to remain limited to 255 characters, as that is the maximum for an indexed field on MySQL with UTF-8 encoding.

I'm closing the issue for now, as it seems unlikely that this would change for the upcoming releases.
