### ISSUE TITLE
Support term groupping

### ISSUE THREAD

**Issue by mnikn** [traduora/traduora#62]
**Is your feature request related to a problem? Please describe.**
Thanks the great piece of work, our team are trying to use traduora and we have about 600 terms. Given the situation, we really need someway to figure out which term use for.

so is it possible to support term group, or term tag?

**Describe the solution you'd like**
In term page, we can add a button called "New group", when it click, it create a new tree, and we can drag the term into group tree. Also, in translation page, we can filter by group.

**Comment by anthonynsimon** [comment]
Hey thanks for the feedback!

The possibility of adding tags to the terms is something that would be
quite beneficial for other features.

What kind of uses would you see for the tags? Mainly filtering or also for
example for being able to export only translations with certain tags?

**Comment by mnikn** [comment]
Right now I think filter by tag is good enough.

**Comment by anthonynsimon** [comment]
#72 should provide this functionality.

**Comment by anthonynsimon** [comment]
The labels feature is now available since version `0.15.0` and should provide this use case.
