### ISSUE TITLE
[discussion] expand on OAuth

### ISSUE THREAD

**Issue by iilei** [traduora/traduora#64]
As #41 is closed and thanks to #44 I am ready to extend the oAuth provider possibilities.

Within this issue I hope to gather feedback regarding the planned implementation.

# Configuration

As configuring everything with env-vars tends to get a bit flimsy I would like to implement the config for auth-providers by utilizing a .traduorarc file [cosmiconfig](https://www.npmjs.com/package/cosmiconfig)

Possibly the cosmiconfig might be merged with config obtained by [habitat](https://www.npmjs.com/package/habitat) to let secrets be managed via env vars still. (option 1.a)

Another option would be providing a cosmiconfig example which picks up process.env vars by itself, as it might be a traduora.config.js (option 1.b) - this would obviously add fewer dependencies.

# Preparing parsing of traduora.config.js

As I think using cosmiconfig with `traduora.config.js` would be the most convenient way to set up / add / alter auth providers, the same config could also be utilzed for the rest of traduora config.

For the scope of the merge request I would solely care about [optional] `authProviders` within the  `traduora.config.js` file.

If you wish I can start with a small merge request by the title _Add cosmiconfig utilization_ or similar so the change set is a bit smaller. The envisioned merge request to _Add auth providers (TBD)_ will be a follow-up then.

For ease of use I'd add a `traduora.config.js.example` file that defines nothing, just has comments in it providing guidance. `traduora.config.js` would be a `.gitignore`´d file, so it comes with no risk of accidental disclosure of confidential information.

Thoughts, @anthonynsimon ?

**Comment by iilei** [comment]
A second thought on Configuration: I might as well simply add migrations and have it in the Database 🙂

**Comment by MatteoJoliveau** [comment]
Having everything configurable via envars is great for containerized deployments. We plan to deploy Traduora on a Kubernetes cluster, so while mounting config files can be an option I think having the ability to choose could be beneficial.

**Comment by anthonynsimon** [comment]
Personally, I've always preferred to be able to configure an application via env vars as much as possible and only resort to config files like `yaml` if the structure of the config needs some taming :)

Nowadays I mainly deploy my apps in a container, so I may be biased towards this method.

That said, we could consider adding support for loading dotenv config files since: 1) they are just env vars in a text file, 2) they are easy to use and familiar to many people and 3) you are not forced to use it.

**Comment by a-florian-h** [comment]
Hello, 
I understand that quite a bit of work has been done on implementing OAuth login. 

I am using the docker image and aligned with the spirit of [#41](https://github.com/ever-co/ever-traduora/issues/41) - keycloak is my preference. 
Looking at package.json I understand [passport](https://github.com/ever-co/ever-traduora/pull/44#issuecomment-510345416) was not brought in. 

Could I kindly ask what is the current status, are changes documented (perhaps I could help) ? I can read from the [configuration](https://docs.traduora.co/docs/configuration) that google signin have env vars. What about openId ? 

Thank you!

**Comment by evereq** [comment]
@a-florian-h It looks like for now only Google provider is supported (passport is used for Guards / JWT Strategy etc, see https://github.com/search?q=repo%3Aever-co%2Fever-traduora%20passport&type=code). 

It feels like some work will need to be done to support other providers (e.g. Keycloak), but it's mostly changes will be needed in the https://github.com/ever-co/ever-traduora/blob/develop/api/src/controllers/auth.controller.ts file and in UI part of course.
