### ISSUE TITLE
Mark translations that need further work/revision

### ISSUE THREAD

**Issue by diogofernandesalves** [traduora/traduora#68]
**Is your feature request related to a problem? Please describe.**
New feature improvement

**Describe the solution you'd like**
Flag translations that require further work/revision so that users can quickly understand and filter by strings that may require further attention or revision from him or other users within the project.
Users would be able to filter by these strings
These strings would be highlighted in another color (orange for example) or with a warning signal.
When selecting a project, users would understand how many strings are requiring work/revision.

**Comment by anthonynsimon** [comment]
Thanks for the feedback!

Being able to add custom tags to translations and filtering by these tags is on the roadmap and would probably solve this issue.

I'm linking this issue to the 1.0 milestone.

**Comment by anthonynsimon** [comment]
#72 should provide this functionality.

**Comment by anthonynsimon** [comment]
The labels feature is now available since version `0.15.0` and should provide this use case.
