### ISSUE TITLE
Present terms requiring translation

### ISSUE THREAD

**Issue by diogofernandesalves** [traduora/traduora#79]
**Is your feature request related to a problem? Please describe.**
New Feature.
Quickly understand what languages have terms without translation (and how many)

**Describe the solution you'd like**
In the menu "Translations", when viewing the list of the languages, next to the language label (on the right), could be displayed something like "25 terms requiring translation".
![image](https://user-images.githubusercontent.com/55490785/66825884-1bd06400-ef43-11e9-9e4d-bd05cd327b1e.png)

This would help users quickly understand where they should focus their attention.

**Comment by ratermir** [comment]
+1
