### ISSUE TITLE
Export to Java Properties charset issue

### ISSUE THREAD

**Issue by giannivh** [traduora/traduora#8]
**Describe the bug**
Exporting to Java properties won't escape accented characters.

**To Reproduce**
1. Add few translations with accented characters (`é`, `è`, `ê`, ...)
2. Export as Java properties

**Expected behavior**
A Java properties file in the ISO-8859-1 charset. (`é` becomes `\u00E9`)

**Actual behavior**
A Java properties file without escaped accented characters. (`é` is still `é`)

**Screenshots**
![Screenshot 01](https://i.imgur.com/GfgWLfM.png)

**Environment**
 - Device: Desktop
 - OS: Arch
 - Browser: Brave; Version 0.60.48 Chromium: 72.0.3626.121 (Official Build) (64-bit)
 - Version: v0.8.7

**Additional context**
Java Properties JavaDoc: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Properties.html

**Comment by anthonynsimon** [comment]
Thanks for reporting that, I think the default Java properties exporting is using unicode as default, instead of ISO-8859-1.

I will change the default encoding as it makes sense for this format, in the future it probably makes sense to expose this and other params via import/export options, but for now that should do.

**Comment by anthonynsimon** [comment]
#11 should fix this, could you give it a try? It's not released yet so you would have to build from source on master.

**Comment by giannivh** [comment]
I just tested and it works! Thanks!

**Comment by kirangk** [comment]
The issue is reproducible with latest version of the docker image.

Gepr\u00fcft instead of Geprüft.

Please, let me know. If there is something needs to be done to fix it.

**Comment by anthonynsimon** [comment]
@kirangk I think you are seeing the right output. The encoding for Java properties files should escape unicode chars (ISO-8859-1). Let me know if anything!

**Comment by kirangk** [comment]
@anthonynsimon ,

I completely do not understand your comment.

I see that this commit https://github.com/traduora/traduora/pull/11/commits/e3f3949a7d7d1be944bd78d9394b4071ff80b8d8 had the ISO-8859-1. 
But later this is over written, https://github.com/traduora/traduora/commit/000ed698dd637207c9bfbcc59f6fdce8c5eb634b

I am not completely sure, that this is causing the issue.

Please correct me if I am wrong.

Thanks

**Comment by anthonynsimon** [comment]
@kirangk 

So I'm not particularly familiar with Java properties files, but the way I understand it is that it's a file encoded in ASCII, using Unicode escapes (`\uxxxx`) for all characters that are not part of the ASCII character set.

So for example, if you wanted to represent the following UTF-8 sequence:

```
term.one = Tous les sociétés
```

It would look like the following in ISO-8859-1:

```
term.one = Tous les soci\u00e9t\u00e9s
```

So internally, we convert it into a UTF-8 sequence to store it in the database and for manipulation. But when exporting it back into a common Java properties file we write it with ISO-8859-1 encoding.

The commits that you mentioned seemed to be that I had switched the library that we use to convert to and from this encoding.

Again I'm not an expert on the topic so might be wrong :)
