### ISSUE TITLE
To add components to the project

### ISSUE THREAD

**Issue by ratermir** [traduora/traduora#84]
many bigger projects are divided into components, that are relatively independent

Components may have life cycle different from each other and translations must follow this life cycle. It woult be useful Traduora be able to create another level - for example "component" that may be managet relatively independently. 
 - component own own files may be exported 
 - all project component files may be  projectexported at once 
 - components will be optional; if I want, i may work at project level, or create components and work with them

**Comment by anthonynsimon** [comment]
Thanks for the feedback!

Being able to add custom tags to translations and filtering by these tags is on the roadmap and would probably solve this issue.

You could for example tag with the component name all the relevant terms and translations and be able to export only this subset if needed.

WIP for this feature is being tracked at #72 .

**Comment by ratermir** [comment]
Thank you for respone. 
Yes, tagging could be a solution - especially if I think about bigger projects with many modules, where every module has (exported) its own properties set but many words are shared across multiple modules. So I am closing this ticket and will wait for tags.
