### ISSUE TITLE
A resource with this value already exists. Please use a different one

### ISSUE THREAD

**Issue by iarts** [traduora/traduora#86]
Im trying to import a .po file but im getting an error (screenshot attachment)
"A resource with this value already exists. Please use a different one."

Im using po edit to generate the po file from source

And here is some contents of the .po file im trying to importing:

msgid ""
msgstr ""
"Project-Id-Version:Test\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-10-24 11:17+0300\n"
"PO-Revision-Date: 2019-10-24 11:18+0300\n"
"Last-Translator: Chris <c@c.gr>\n"
"Language-Team: Test <support@cc.gr>\n"
"Language: en_GB\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Poedit-KeywordsList: T_;_;gettext;gettext_noop\n"
"X-Poedit-Basepath: ../../..\n"
"X-Poedit-SourceCharset: UTF-8\n"
"X-Generator: Poedit 2.1.1\n"
"X-Poedit-SearchPath-0: .\n"
"X-Poedit-SearchPath-1: includes\n"

#: 404.php:12 404.php:50
msgid ""
"Μπορεί να έχετε πληκτρολογήσει εσφαλμένα τη διεύθυνση URL Ή η σελίδα έχει "
"καταργηθεί"
msgstr "You may have entered the URL incorrectly OR the page has been removed"

#: agency-list.php:9
msgid "Λίστα Μεσιτών, Μεσιτικά Γραφεία"
msgstr "List of Realtors, Real Estate Agents"

#: agency-list.php:14
msgid "Βρείτε μεσιτικό γραφείο στην περιοχή σας"
msgstr "Find a real estate agency in your area"

#: agency-list.php:148 includes/slider.php:163 index.php:264 index.php:594
#: results.php:1181 results.php:1326
msgid "Βρέθηκαν"
msgstr "found"

#: agency-list.php:148
msgid "ενεργά γραφεία"
msgstr "Description"

#: agency-list.php:256 results.php:1192
#, fuzzy
#| msgid "Επιλέξτε Υποκατηγορία"
msgid "Ακίνητα ανα κατηγορία"
msgstr "Category"

#: agency-list.php:286 property.php:1105 results.php:1222
#, fuzzy
#| msgid "Μονοκατοικία"
msgid "Κατοικίες"
msgstr "Detached house"

#: agency-list.php:287 property.php:1106 results.php:1223
#, fuzzy
#| msgid "Επαγγελματικό"
msgid "Επαγγελματικοί Χώροι"
msgstr "Rooms"

![err](https://user-images.githubusercontent.com/6687238/70147363-b845f580-16ac-11ea-96a4-6f841a7d1d61.png)

**Comment by anthonynsimon** [comment]
I couldn't reproduce the issue locally, could you please try again with the latest version of traduora? I tried with 0.13.0 and 0.14.0 and it worked fine in both cases.

Which version were you using when this issue happened?

**Comment by rochadk** [comment]
I'm experiencing the exact same error with a very large .po file. I've got 0.14.0.

**Comment by iarts** [comment]
I showed you a small part of the file and not the whole file. the original file is a vary large .po file. I've got 0.13.0

**Comment by anthonynsimon** [comment]
Could you somehow break down the file into smaller parts until you find the section with the terms that are causing this issue?

I would need to reproduce the issue in order to be able to debug it.

Also it would be great if you can post any errors/stack traces that you find on the server logs.

**Comment by iarts** [comment]
Ohh this is going to be very time consuming because the .po file is very large!
Υes i would like to search in logs files but, where can i find the logs files? (I don't see anything in apache's log files)

**Comment by anthonynsimon** [comment]
I tried reproducing your issue by generate very large fake .po files, but wasn't able to.

I'd need more info or a way to reproduce this in order to debug it properly.

The logs are on the STDOUT of the application itself, not on the load balancer/reverse-proxy.

**Comment by iarts** [comment]
At stdout am getting the following:
`traduora_1  | 172.18.0.1 - POST /api/v1/projects/e5864d7c-010b-434c-a084-3b780be6c2c7/imports?format=po&locale=en_US HTTP/1.1 409 75 - 436.499 ms`

im sending you the .po file to reproduce the error, simply change the extension to .po from .txt

[messages.txt](https://github.com/traduora/traduora/files/3956838/messages.txt)

**Comment by anthonynsimon** [comment]
Thanks for sharing the file! I was able to find the issue.

One or more of your terms is too long:

```
code: 'ER_DATA_TOO_LONG',
[0]   errno: 1406,
[0]   sqlMessage: 'Data too long for column \'value\' at row 1',
[0]   sqlState: '22001',
[0]   index: 0,
Η υποβολή της αίτησης ανάθεσης δεν αποτελεί δεσμευτικό νομικό έγγραφο.
Σκοπός της είναι η επικοινωνία, μεταξύ του ιδιοκτήτη και του γραφείου μας.
Η έναρξη οποιασδήποτε συνεργασίας πραγματοποιείτε μετά την επικοινωνία
και μόνο με την σύμφωνη γνώμη και των δύο πλευρών
```

The terms are limited to 255 characters for performance/indexing, translation values on the other hand are practically "unlimited text".

Think of terms as the "string keys" that group together the translations across multiple languages. You might need to update the input structure into something more like:

```
msgid ""
msgstr ""
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"MIME-Version: 1.0\n"
"Language: en_US\n"

msgid "welcome.message"
msgstr "Hello there, welcome to my app!"

msgid "button.accept"
msgstr "Accept terms and conditions"
```

In which in a Gettext file the `msgid` is the term in traduora and the `msgstr` is the actual text translation (can be long text).

**Comment by anthonynsimon** [comment]
The error message was not helpful enough on the webapp, I will improve it so it's clearer what is the issue for next time. Thanks a lot once again!
