### ISSUE TITLE
Display project's translation rate

### ISSUE THREAD

**Issue by BenDz** [traduora/traduora#9]
**Is your feature request related to a problem? Please describe.**
No, just a way to have a better view of the project translation progress.

**Describe the solution you'd like**
It could be displayed on multiple components:
* On the left sidebar, near the project title. This would represent the global translation rate, all locales together (number of translations / number of terms * number of locales)
* On the translations view, on each locale card. This would represent the number of translated terms / number of terms
* On the terms view, on each term card. This would represent the number of translated locales for this term / number of locales

I unfortunately don't manage to setup my environment to work on it...
Thanks!

**Comment by anthonynsimon** [comment]
@BenDz hey about not being able to setup the dev environment, what issue are you having?

You can use one of the helper scripts on a fresh repo:

```sh
yarn && bin/start-dev.sh
```
The API will be listening on `localhost:8080` and the web app on `localhost:4200`, both with hot code reload.

**Comment by BenDz** [comment]
@anthonynsimon 	Thanks! I managed to set it up.
I'll try to play around with that, but I'm not sure I'll be able to PR anything on it.

**Comment by anthonynsimon** [comment]
This is partially solved by #89
